# Generated by Django 4.2 on 2023-05-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="content",
            field=models.TextField(null=True),
        ),
    ]
